### ISSUE TITLE
🐛 BUG: `source-trello` `cards` stream failing

### ISSUE THREAD

**Issue by nabdoni** [airbytehq/PyAirbyte#206]
When trying to replicate data from the `cards` stream of the `source-trello` connector, an exception is thrown:

```
        Marking stream cards as STARTED
    Syncing stream: cards 
    Encountered an exception while reading stream cards
    Traceback (most recent call last):
      File "/Users/CENSORED/Documents/backup_data/pyairbyte_ingest_piece/.venv-source-trello/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
        yield from self._read_stream(
      File "/Users/CENSORED/Documents/backup_data/pyairbyte_ingest_piece/.venv-source-trello/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 237, in _read_stream
        for record_data_or_message in record_iterator:
      File "/Users/CENSORED/Documents/backup_data/pyairbyte_ingest_piece/.venv-source-trello/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 135, in read
        for _slice in slices:
      File 
"/Users/CENSORED/Documents/backup_data/pyairbyte_ingest_piece/.venv-source-trello/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/stream_slicers/cartesian_product_stream_slicer.py",
line 106, in stream_slices
        partition = dict(ChainMap(*[s.partition for s in stream_slice_tuple]))
      File 
"/Users/CENSORED/Documents/backup_data/pyairbyte_ingest_piece/.venv-source-trello/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/stream_slicers/cartesian_product_stream_slicer.py",
line 106, in <listcomp>
        partition = dict(ChainMap(*[s.partition for s in stream_slice_tuple]))
    AttributeError: 'dict' object has no attribute 'partition'
    Marking stream cards as STOPPED
```

The connector source and configuration pass `.check()`, and the `boards` stream works as intended with the same configuration.

Used configuration:
```
{
    "source": "source-trello",
    "config": {
        "key": "CENSORED_KEY",
        "token": "CENSORED_TOKEN",
        "start_date": "2023-03-01T00:00:00Z"
    },
    "streams": [
        "cards"
    ]
}
```

**Comment by aaronsteers** [comment]
@nabdoni - Thanks for raising this issue.

What I notice about the stack trace is that the error seems to stem from the `source-trello` source code itself, and not from a PyAirbyte-specific call.

It might be worth searching the main `airbyte` repo to see if anyone has reported a similar issue... 🤔

**Comment by aaronsteers** [comment]
cc @marcosmarxm - I see you've reviewed some other Trello PRs recently. Lmk if you have an idea on possible root cause.
