### ISSUE TITLE
AirbyteConnectorMissingCatalogError while trying to read source-azure-blob-storage

### ISSUE THREAD

**Issue by IronJayx** [airbytehq/PyAirbyte#280]
Hi,

I am getting a catalag error while trying to connect/ read from Azure storage. 

Any idea on why ? 

All help would be much appreciated, thanks !

Here is my code:

```
import os
import airbyte as ab
from dotenv import load_dotenv

load_dotenv()


# Configure and read from the source
read_result = ab.get_source(
    "source-azure-blob-storage",
    config={
        "authentification": ["airbytehq/pyAirbyte"],
        "credentials": {
            "auth_type": "storage_account_key",
            "azure_blob_storage_account_key": os.environ.get('AZURE_STORAGE_ACCOUNT_KEY')
        },
        "azure_blob_storage_account_name": os.environ.get('AZURE_STORAGE_ACCOUNT_NAME'),
        "azure_blob_storage_container_name": os.environ.get('AZURE_STORAGE_CONTAINER_NAME')
    },
).read()

print(read_result)
```

Here is the error:

```
Traceback (most recent call last):
  File "/root/airvector/examples/airbyte_test.py", line 20, in <module>
    ).read()
  File "/root/.cache/pypoetry/virtualenvs/airvector-JnIzwmfs-py3.10/lib/python3.10/site-packages/airbyte/sources/base.py", line 708, in read
    available_streams=self.get_available_streams(),
  File "/root/.cache/pypoetry/virtualenvs/airvector-JnIzwmfs-py3.10/lib/python3.10/site-packages/airbyte/sources/base.py", line 222, in get_available_streams
    return [s.name for s in self.discovered_catalog.streams]
  File "/root/.cache/pypoetry/virtualenvs/airvector-JnIzwmfs-py3.10/lib/python3.10/site-packages/airbyte/sources/base.py", line 320, in discovered_catalog
    self._discovered_catalog = self._discover()
  File "/root/.cache/pypoetry/virtualenvs/airvector-JnIzwmfs-py3.10/lib/python3.10/site-packages/airbyte/sources/base.py", line 186, in _discover
    raise exc.AirbyteConnectorMissingCatalogError(
airbyte.exceptions.AirbyteConnectorMissingCatalogError: AirbyteConnectorMissingCatalogError: Connector did not return a catalog.

Log output:
        Error starting the sync. This could be due to an invalid configuration or catalog. Please contact Support for assistance.
```

**Comment by aaronsteers** [comment]
@IronJayx - Thanks for reporting. I can say this is a factor of needing improve logging for when users try to invoke Docker-based connectors. TLDR: I think this is written in Java, and therefor requires to be run through the new (experimental) docker executor.

Here are some suggestions we could apply that might remove/reduce confusions:

1. We can and should clarify this error so that it reads: "Could not be found in the connector registry" - which would be more clear messaging than what we have presently.
2. We should provide alternative messaging if the connector exists, but is not written in Python. I think that is what is happening in this case - and we could direct users to use the docker-based implementation in these cases.


Wdyt? Is this helpful at all?

**Comment by aaronsteers** [comment]
@IronJayx - At first I thought this was due the connector being in Java (it's not). Looking more closely, I think what is happening is that the connector is not able to discover any streams. I believe you need to also specify a `streams` collection.

<img width="733" alt="image" src="https://github.com/airbytehq/PyAirbyte/assets/18150651/71a087f7-790e-436f-8912-6ff90c91baae">

https://docs.airbyte.com/integrations/sources/azure-blob-storage#reference

**Comment by IronJayx** [comment]
Thanks @aaronsteers that waws correct ! 

Now I want to disable parser to process unstructured data (images/ videos) but I guess that is for another issue. 

```python
import os
import airbyte as ab
from dotenv import load_dotenv

load_dotenv()


# Configure and read from the source
source = ab.get_source(
    "source-azure-blob-storage",
    install_if_missing=True,
    config={
        # "authentification": ["airbytehq/pyAirbyte"],
        "credentials": {
            "auth_type": "storage_account_key",
            "azure_blob_storage_account_key": os.environ.get('AZURE_STORAGE_ACCOUNT_KEY')
        },
        "azure_blob_storage_account_name": os.environ.get('AZURE_STORAGE_ACCOUNT_NAME'),
        "azure_blob_storage_container_name": os.environ.get('AZURE_STORAGE_CONTAINER_NAME'),
        "streams": [{
            "name": "all",
            "format": {
                "filetype": "unstructured",
                "skip_unprocessable_files": False,
                
            },
            "globs": ["**"]
        }]
    },
)

source.check()
```
