### ISSUE TITLE
Fix: Use User-Level Directories for Temporary Files and Mount Points

### ISSUE THREAD

**Issue by niyasrad** [airbytehq/PyAirbyte#367]
# Description

- The source-postgres connector failed to connect due to an error in accessing a system-level temporary directory, which is not accessible in the Colima setup. This caused the connector to be unable to find the required file, resulting in a failure.

## **Traceback**

```
Traceback (most recent call last):
  File "/Users/niyashameed/Work/pyairbyte/pyairbyte-test.py", line 29, in <module>
    source.check()
  File "/Users/niyashameed/Work/pyairbyte/venv/lib/python3.10/site-packages/airbyte/_connector_base.py", line 323, in check
    raise exc.AirbyteConnectorCheckFailedError(
airbyte.exceptions.AirbyteConnectorCheckFailedError: Connector check failed. (AirbyteConnectorCheckFailedError)
------------------------------------------------------------
AirbyteConnectorCheckFailedError: Connector check failed.
    Please review the log file for more information.
    More info: https://docs.airbyte.com/integrations/sources/postgres
    Connector Name: 'source-postgres'
    Failure Reason: 'Could not connect with provided configuration. Error: java.nio.file.NoSuchFileException: /var/folders/y1/17qgs7nn6zs78llyhbg40yy80000gn/T/tmpuoj7d8iv.json'
    Log file: /tmp/airbyte/logs/source-postgres/source-postgres-log-J7P6JWMMC.log
```

# RCA

The root cause of this failure is that the directories for temporary files and mount points were set to system-level paths, which are not accessible in the Colima container environment. This led to the NoSuchFileException because the expected file path could not be resolved.

## Additional Details
Observed with MacOS 12.4 (M1, 2020) - With a colima setup for docker. When using Docker Desktop, the path is getting resolved properly.

**Comment by niyasrad** [comment]
Fixed and Implemented with #368 and #370
